language: go

go:
  - 1.15.x

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./pkg
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)